spring:
    thymeleaf:
        cache: false
        mode: HTML
        encoding: utf-8
    profiles:
        active: dev
project:
    salt: "blog"
    pageSize: 5
    avatar: /images/avatar.jpg
    adminAvatar: https://picsum.photos/id/0/100/100
    email: 1249041911@163.com

